# Generated by Django 5.2.12 on 2026-03-30 21:20

from django.db import migrations, models


def migrate_legacy_order_statuses(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="approved").update(status="client_approved")
    Order.objects.filter(status="completed").update(status="expired")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('client_approved', 'Cliente aprobado'), ('art_approved', 'Arte aprobado'), ('invoiced', 'Facturada'), ('paid', 'Pagada'), ('permit_pending', 'Permiso alcaldía'), ('installation', 'Instalación'), ('active', 'Activa'), ('expired', 'Vencida'), ('cancelled', 'Cancelada'), ('rejected', 'Rechazada')], default='draft', max_length=32),
        ),
        migrations.RunPython(migrate_legacy_order_statuses, migrations.RunPython.noop),
    ]
