# Generated by Django 5.2.12 on 2026-04-22 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_workflow_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderartattachment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderartattachment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).'),
        ),
        migrations.AlterField(
            model_name='orderartattachment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderinstallationpermit',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderinstallationpermit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).'),
        ),
        migrations.AlterField(
            model_name='orderinstallationpermit',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
