# Generated by Django 6.0.3 on 2026-03-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('billboard', 'Billboard'), ('banner', 'Banner'), ('elevator', 'Elevator'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('location_description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('shopping_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_spaces', to='malls.shoppingcenter')),
            ],
            options={
                'ordering': ['shopping_center', 'code'],
            },
        ),
    ]
