# Generated by Django 5.2.12 on 2026-03-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/spaces/%Y/%m/'),
        ),
    ]
