# Generated by Django 5.2.12 on 2026-03-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0002_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='double_sided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adspace',
            name='hem_pocket_top_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hueco superior tipo bolsillo (ej. 4,5 cm en pendones balcón).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='adspace',
            name='installation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adspace',
            name='production_specs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adspace',
            name='venue_zone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adspace',
            name='type',
            field=models.CharField(choices=[('billboard', 'Valla (genérico)'), ('banner', 'Banner / pendón (genérico)'), ('elevator', 'Ascensor'), ('other', 'Otro'), ('valla_vertical', 'Valla vertical / gigantografía vertical'), ('valla_horizontal', 'Valla horizontal / gigantografía horizontal'), ('gigantografia_fachada', 'Gigantografía en fachada'), ('pendon_balcon', 'Pendón de balcón'), ('pendon_atrio', 'Pendón de atrio / colgante central'), ('pendon_pasillo', 'Pendón de pasillo'), ('pendon_plaza', 'Pendón de plaza'), ('pendon_columna', 'Pendón de columna')], max_length=32),
        ),
    ]
