# Generated by Django 5.2.12 on 2026-03-31 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0003_pdf_and_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adspace',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).'),
        ),
        migrations.AddField(
            model_name='adspace',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
