# Generated by Django 5.2.12 on 2026-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0007_adspaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspace',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Primera imagen de la galería (sincronizada al guardar).', null=True, upload_to='covers/spaces/%Y/%m/'),
        ),
    ]
