# Generated by Django 5.2.12 on 2026-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0008_alter_adspace_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspace',
            name='code',
            field=models.CharField(db_index=True, help_text='Código único de la toma: prefijo-T{número}[sufijo], ej. SCC-T1, SLC-T1A (el prefijo no depende del centro).', max_length=32, unique=True),
        ),
    ]
