# Generated by Django 6.0.3 on 2026-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
