# Generated by Django 5.2.12 on 2026-03-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0002_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcenter',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shoppingcenter',
            name='country',
            field=models.CharField(blank=True, default='Venezuela', max_length=120),
        ),
        migrations.AddField(
            model_name='shoppingcenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shoppingcenter',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shoppingcenter',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
