# Generated by Django 5.2.12 on 2026-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0004_homepage_listing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcenter',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], db_index=True, default='active', help_text='Activo: visible en operaciones habituales. Inactivo: oculto del catálogo público.', max_length=16),
        ),
    ]
