# Generated by Django 5.2.12 on 2026-03-31 11:14

import django.utils.timezone
from django.db import migrations, models


def copy_status_to_is_active(apps, schema_editor):
    ShoppingCenter = apps.get_model("malls", "ShoppingCenter")
    for row in ShoppingCenter.objects.all():
        if getattr(row, "status", None) == "inactive":
            row.is_active = False
            row.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("malls", "0005_shopping_center_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcenter",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="shoppingcenter",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Si está desmarcado, el registro se considera inactivo (no borrado).",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcenter",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(copy_status_to_is_active, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="shoppingcenter",
            name="status",
        ),
    ]
