# Generated by Django 5.2.12 on 2026-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0008_shoppingcenter_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcenter',
            name='listing_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden en ese listado de centros (menor primero).'),
        ),
        migrations.AlterField(
            model_name='shoppingcenter',
            name='on_homepage',
            field=models.BooleanField(db_index=True, default=True, help_text='Si se incluye en el listado público GET /api/centers/ (la portada del sitio lista tomas).'),
        ),
    ]
