# Generated by Django 5.2.12 on 2026-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_client_help_text_and_workspace_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador marketplace'), ('client', 'Cliente marketplace')], db_index=True, default='client', max_length=16),
        ),
    ]
