# Generated by Django 5.2.12 on 2026-04-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_status_active_suspended_only'),
        ('users', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Empresa que este usuario representa (como mucho una). Obligatorio si el rol es cliente marketplace. Varios usuarios pueden compartir la misma empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='clients.client'),
        ),
    ]
