# Generated by Django 5.2.12 on 2026-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspace_phone_country_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(help_text='Nombre comercial del owner (marca operadora del marketplace).', max_length=200),
        ),
    ]
