# Generated by Django 5.2.12 on 2026-03-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/clients/%Y/%m/'),
        ),
    ]
