# Generated by Django 5.2.12 on 2026-03-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
