# Generated by Django 5.2.12 on 2026-04-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_rif_optional'),
        ('workspaces', '0005_alter_workspace_is_active_alter_workspace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(help_text='Tenant al que pertenece la empresa cliente (RIF único por workspace cuando está indicado).', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='workspaces.workspace'),
        ),
    ]
