# Generated by Django 5.2.12 on 2026-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_representative_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='representative_id_number',
            field=models.CharField(blank=True, help_text='Cédula de identidad del representante (ej. V-17.311.805).', max_length=32),
        ),
        migrations.AlterField(
            model_name='client',
            name='representative_name',
            field=models.CharField(blank=True, help_text='Representante legal o firmante (hoja de negociación, cartas).', max_length=255),
        ),
    ]
